      PROGRAM CDSTAT
C CREATE A DATA FILE FOR A STATISTICS EXAMPLE
        IMPLICIT NONE
        CHARACTER*64 OFNAM
C FIRST ROW OF THE FILE IS THE NUMBER OF POINTS CONTAINED
        INTEGER NPTS,I
        REAL GRCR
40      PRINT *,'HOW MANY POINTS DO YOU WANT TO GENERATE? (<= 1000)'
        READ *,NPTS
        IF (NPTS.GT.1000) GOTO 40
        OFNAM='statpoints001.txt'
        OPEN(11,FILE=OFNAM,ERR=9000)
        WRITE(11,'(I4)',ERR=9100) NPTS
        CALL INIRAN
        DO 10,I=1,NPTS
          WRITE(11,100,ERR=9100) GRCR(NPTS)
10      CONTINUE
        CLOSE(11)
        GOTO 9999
100     FORMAT(F12.4)
9000    PRINT *,'ERROR IN OPENING OUTPUT FILE',OFNAM
        GOTO 9999
9100    PRINT *,'ERROR IN WRITING OUTPUT DATA'
9999    STOP
      END
