      PROGRAM INQUIR
        CHARACTER*64 IFNAM
        CHARACTER*4 STRING(10)
        INTEGER I(10),CNT,N
        LOGICAL LOP,LEX
        CHARACTER*10 FMT,ACC,B
        REAL F(10)
        IFNAM='result001.txt'
        INQUIRE(FILE=IFNAM,OPENED=LOP,NUMBER=N,EXIST=LEX)
        IF(LEX) PRINT 110,IFNAM
        IF(LOP)THEN
            PRINT *,IFNAM(1:12),' OPENED ON UNIT ',N
        ELSE
            OPEN(11,FILE=IFNAM,ERR=9000)
        ENDIF
        INQUIRE(UNIT=11,OPENED=LOP,NUMBER=N,FORMATTED=FMT,ACCESS=ACC
     & ,BLANK=B)
        IF(LOP)THEN
            PRINT *,IFNAM(1:12),' OPENED ON UNIT ',N
            PRINT *,'ACCESS = ',ACC
            PRINT *,'BLANK = ',B
        ELSE
            CONTINUE
        ENDIF
        PRINT *,IFNAM(1:12),' IS FORMATTED? ',FMT
        CNT=1
80      READ(11,100,END=90,ERR=9100)STRING(CNT),I(CNT),F(CNT)
        PRINT 100,STRING(CNT),I(CNT),F(CNT)
        CNT=CNT+1
        GOTO 80
90      CLOSE(11)
        PRINT *,'READ ',CNT-1,' RECORDS'
        GOTO 9999
100     FORMAT(A4,1X,I4,1X,F6.2)
110     FORMAT('FILE ',A12,' EXISTS')
9000    PRINT *,'ERROR IN OPENING INPUT FILE ',IFNAM
        GOTO 9999
9100    PRINT *,'ERROR IN READING DATA '
9999    STOP
      END
