      PROGRAM LOAN
        IMPLICIT NONE
        REAL AMOUNT,PCRATE,RATE,REPAY
        INTEGER YEARS,I
        PRINT *,'ENTER AMOUNT($), %RATE, YEARS'
        READ *,AMOUNT,PCRATE,YEARS
        RATE = PCRATE/100.0
        REPAY = RATE*AMOUNT/(1-(1.0+RATE)**(-YEARS))
        PRINT 100,REPAY
        PRINT *,'END OF YEAR BALANCE'
        DO 15,I=1,YEARS
          AMOUNT = AMOUNT + (AMOUNT*RATE) - REPAY
           IF (AMOUNT.LT.0.01) AMOUNT=0.00
           PRINT 200,I,AMOUNT
15      CONTINUE
100   FORMAT('YEARLY REPAY IS ',F8.2,' $')
200   FORMAT(I3,8X,F8.2)
        STOP
      END
