FC=f77
FD=f77
OEXT=.o
EEXT=
RM=rm -rf
FFLAGS=
FDFLAGS=
LIBS=
SRCS=sales1.f

OBJS = $(SRCS:.f=$(OEXT))
TARGETS = $(OBJS:$(OEXT)=$(EEXT))
.PHONY: all clean

all: $(OBJS) $(TARGETS)

.f.o:
	$(FC) -c $(FFLAGS) -o $@ $<

.o$(EEXT):
	$(FD) -o $@ $^ $(FDFLAGS) $(LIBS)

clean:
	$(RM) $(OBJS) $(TARGETS)

