C THIS PROGRAM READ THE PARTICLES EMITTED FROM AN EXPERIMENTAL LOG FILE
C FOR EACH TIME INTERVAL IT WRITES: A SEQUENTIAL NUMBER
C THE LENGTH IN SECONDS OF THE INTERVAL
C THE READING FOR ALPHA,BETA AND GAMMA RELATED TO THAT TIME INTERVAL
C THE AVERAGE RATE (IN SECONDS) FOR ALPHA,BETA,GAMMA PARTICLES
C AFTER 1000 TIME INTERVALS READ, PRINT THE TIME INTERVAL THAT
C HAD THE HIGHEST EMISSION RATE OF GAMMA RADIATION
C 1) Initialize maximum radiation and interval
C 2) Print column headings
C 3) REPEAT 100O TIMES
C   3.1) READ next set of data
C   3.2) compute length of time interval and average emissions
C   3.3) Print details
C   3.4) If rate of gamma is > current maxgamma
C     3.4.1) save gamma as maxgamm
C 4) Print details of max. gamma radiation
      PROGRAM PRRAD
        IMPLICIT NONE
        INTEGER TIME,LTIME,MAXTIME,ALPHA,BETA,GAMMA
        REAL RTIME,ALPHAR,BETAR,GAMMAR,MAXGAM
        CHARACTER*64 IFNAM,OFNAM
        INTEGER I,IMG
        DATA ALPHAR/0.0/,BETAR/0.0/,GAMMAR/0.0/
        IFNAM='rad001.log'
        OFNAM='rates001.txt'
        OPEN(11,FILE=IFNAM,ERR=9100)
        OPEN(12,FILE=OFNAM,ERR=9300)
        LTIME=0
        I=1
        WRITE(12,120,ERR=9400)'  n.','len','alphas','betas','gams'
     & ,'alfrat','betrat','gamrat'
70        READ(11,100,ERR=9200,END=80)TIME,ALPHA,BETA,GAMMA
          RTIME=(TIME-LTIME)/100.0
          ALPHAR=ALPHA/RTIME
          BETAR=BETA/RTIME
          GAMMAR=GAMMA/RTIME
          LTIME=TIME
          WRITE(12,110,ERR=9400)I,RTIME,ALPHA,BETA,GAMMA
     & ,ALPHAR,BETAR,GAMMAR
          IF (GAMMAR.GT.MAXGAM) THEN
            MAXGAM=GAMMAR
            IMG=I
          END IF
C          IF (I.EQ.1000) GOTO 90
          I=I+1
        GOTO 70
80      PRINT *,'END OF FILE REACHED'
90      CLOSE(11)
        CLOSE(12)
        PRINT *,'MAXIMUM GAMMA RATE REACHED ON '
        PRINT 130,IMG,MAXGAM
        GOTO 9999
100     FORMAT(I10,5X,I6,5X,I6,5X,I6)
110     FORMAT(I5,3X,F8.2,3X,I6,3X,I6,3X,I6,F8.2,3X,F8.2,3X,F8.2)
120     FORMAT(A4,3X,A8,3X,A6,3X,A6,3X,A6,A8,3X,A8,3X,A8)
130     FORMAT('INTERVAL N. ',I5,' GAMMA RATE',F8.2,' PARTICLE/S')
9100    PRINT *,'ERROR IN OPENING INPUT FILE ',IFNAM
        GOTO 9999
9200    PRINT *,'ERROR IN READING PARTICLE RATES'
        GOTO 9999
9300    PRINT *,'ERROR IN OPENING OUTPUT FILE ',OFNAM
        GOTO 9999
9400    PRINT *,'ERROR IN WRITING PARTICLE AVERAGES'
        GOTO 9999
9999    STOP
      END
