C EXPERIMENT MONITORING RADIOACTIVE DECAY OF A SPECIMEN
C IT PRODUCES A LOG CONTAINING TIME TAGGED DATA SAMPLINGS
C AT APPROXIMATELY REGULAR INTERVAL THE APPARATUS SAVES THE TIME
C IN HUNDREDTHS OF A SECOND (10^2 S), THE NUMBER OF ALPHA PARTICLES
C EMITTED IN THAT TIME INTERVAL, THE N. OF BETA PARTICLES EMITTED IN THAT
C TIME INTERVAL AND THE AMOUNT OF GAMMA RADIATION EMITTED IN THE SAME PERIOD
C THIS OUTPUT IS SAVED IN AN ASCII LOG FILE EACH RECORD (ROW) CONSISTING
C OF 8 DIGITS NUMBER FOR THE TIME AND 3x6 DIGITS NUMBER FOR THE PARTICLES SAMPLINGS
C THERE ARE 5 SPACES BETWEEN EACH NUMBER. AN EXAMPLE EXPERIMENT RUN LASTS 40 HOURS
C AND EMISSIONS ARE SAMPLED APPROXIMATELY EVERY 1 MINUTE.
      PROGRAM RAD1
      INTEGER TIME,WTIME,MAXTIME,ALPHA,BETA,GAMMA
      INTEGER S,TERR
      PARAMETER(MAXTIME=288000000)
      CHARACTER*64 OFNAM
      CALL INIRAN
      OFNAM='rad001.log'
      OPEN(11,FILE=OFNAM,ERR=9000)
      DO 10,TIME=1,MAXTIME
        IF(MOD(TIME,12000).EQ.0) THEN
          TERR=GRC(3500)
          S=GRC(2)
          IF(S.EQ.0) TERR=-1*TERR
          WTIME = TIME + TERR
          ALPHA=GRC(600)
          BETA=GRC(1000)
          GAMMA=GRC(800)
          WRITE(11,100,ERR=9100)WTIME,ALPHA,BETA,GAMMA
        END IF
10    CONTINUE
      CLOSE(11)
      GOTO 9999
100   FORMAT(I10,5X,I6,5X,I6,5X,I6)
9000  PRINT *,'ERROR IN OPENING OUTPUT FILE ', OFNAM
      GOTO 9999
9100  PRINT *,'ERROR IN WRITING DATA ON OUTPUT FILE'
9999  STOP
      END
