      PROGRAM STATS1
        IMPLICIT NONE
        LOGICAL DEBUG
        INTEGER NPTS,I
        CHARACTER*64 IFNAM
        REAL V(1000),AVG,STD
        DEBUG=.TRUE.
        IFNAM='statpoints001.txt'
        OPEN(11,FILE=IFNAM,ERR=9000)
        READ(11,'(I4)',ERR=9100)NPTS
        IF(DEBUG)PRINT *,'GOING TO READ ',NPTS,' POINTS'
        READ(11,100,ERR=9200) (V(I),I=1,NPTS)
        CLOSE(11)
        CALL MEANSD(V,NPTS,AVG,STD)
        PRINT *,'AVG: ',AVG,' STD: ',STD
        GOTO 9999
100     FORMAT(F12.4)
9000    PRINT *,'ERROR IN OPENING INPUT FILE'
        GOTO 9999
9100    PRINT *,'ERROR IN READING N. OF POINTS'
        GOTO 9999
9200    PRINT *,'ERROR IN READING A POINT'
9999    STOP
      END

      SUBROUTINE MEANSD(V,NPTS,AVG,STD)
C INPUTS: V IS THE INPUT ARRAY, NPTS IS THE DIMENSION OF V
C OUTPUTS: AVG IS THE RETURNED MEAN AND STD IS THE RETURNED STANDARD DEVIATION
      IMPLICIT NONE
      INTEGER NPTS,I
      REAL V(1000),SUM1,SUMQ,AVG,STD
      DATA SUM1/0.0/,SUMQ/0.0/
      DO 10,I=1,NPTS
        SUM1=V(I)+SUM1
        SUMQ=V(I)**2+SUMQ
10    CONTINUE
      AVG=SUM1/NPTS
      STD=SQRT((SUMQ-NPTS*AVG)/(NPTS-1))
      RETURN
      END
