C SURVEY ON OCCUPATION IN A REGION
C THE SURVEY DATA ARE SAVED IN AN ASCII FILE
C WITH THE FOLLOWING FORMAT:
C Columns 1-20    Name
C Column    23    Sex
C                  0 if male
C                  1 if female
C Column    25    job status
C                  1 if in full time education        --> columns 28,29 Age
C                  2 if in full time employement      --> columns 28,31 monthly salary ($)
C                  3 if in part time employement      --> columns 28,31 monthly salary ($)
C                                                         columns 34,37 other monthly income
C                  4 if temporarily unemployed        --> columns 28,29 Age
C                                                         columns 32,34 n. of months unemployed
C                  5 if not working or searching job  --> columns 28,29 Age
C                                                         column  31    Code = 1 if looking after children
C                                                                            = 2 if looking after other relatives
C                                                                            = 3 for any other reason
      PROGRAM CJS
        IMPLICIT NONE
        INTEGER I,N
        INTEGER GRC,GRCV
        PARAMETER(N=1004)
        CHARACTER*20 NAME(N)
        CHARACTER*20 TEMPN
        CHARACTER*80 SFN
        INTEGER SEX(N),JS(N),AGE(N),SALARY(N),OSAL(N)
C NMU=NUMBER OF MONTHS UNEMPLOYED
C NWC=NON WORKING CODE
        INTEGER NMU(N),NWC(N)
        DATA SFN/'jobsurvey001.txt'/
      DATA SEX /1,0,
     & 1,0,1,1,1,0,0,1,1,0,
     & 0,0,0,0,0,1,0,1,0,1,
     & 0,0,0,1,0,1,0,1,0,0,
     & 0,1,0,0,1,1,0,1,0,1,
     & 1,1,1,1,1,0,0,1,1,0,
     & 0,1,0,0,0,0,0,0,1,0,
     & 0,0,0,0,0,1,1,0,0,0,
     & 1,1,1,0,0,0,0,0,1,0,
     & 0,1,1,0,0,0,1,0,0,0,
     & 0,1,0,0,1,0,1,1,0,1,
     & 1,1,0,0,0,0,0,0,0,1,
     & 0,0,0,0,1,0,0,0,0,0,
     & 0,1,1,1,1,1,1,1,0,0,
     & 0,1,1,1,1,1,1,1,0,0,
     & 0,0,0,0,0,1,1,0,1,1,
     & 1,0,0,0,1,0,1,0,1,1,
     & 0,1,0,0,0,1,1,0,0,1,
     & 0,0,0,0,1,0,0,0,1,1,
     & 1,0,1,0,0,0,0,0,1,1,
     & 1,1,0,0,1,1,1,1,1,0,
     & 0,1,0,0,1,1,1,1,1,0,
     & 1,1,0,0,1,0,1,1,0,0,
     & 0,0,1,0,0,1,1,1,0,0,
     & 1,0,1,0,1,1,1,0,0,1,
     & 0,1,0,0,0,1,0,1,0,1,
     & 1,0,1,0,0,1,1,0,0,1,
     & 0,0,0,0,0,1,1,1,1,1,
     & 0,1,1,0,1,1,1,1,0,1,
     & 0,1,1,1,1,0,0,1,0,1,
     & 0,0,1,0,0,1,1,1,0,0,
     & 1,1,1,0,1,0,1,1,0,1,
     & 0,0,0,0,0,1,0,0,0,0,
     & 1,1,0,0,1,1,1,1,0,0,
     & 1,1,1,1,1,0,1,0,1,1,
     & 1,0,0,1,0,0,1,0,0,1,
     & 0,0,0,0,0,0,1,0,1,0,
     & 0,0,1,1,1,1,1,1,1,1,
     & 0,1,1,0,0,1,0,1,1,1,
     & 1,1,1,1,1,1,1,1,1,0,
     & 1,1,1,0,0,0,1,0,1,1,
     & 1,0,0,0,0,0,1,1,0,0,
     & 0,1,1,1,0,0,0,0,1,0,
     & 0,0,1,1,1,0,0,0,0,1,
     & 1,1,1,1,1,0,0,0,1,0,
     & 0,1,1,1,0,1,1,0,1,1,
     & 0,0,1,0,1,0,0,1,1,0,
     & 1,0,1,0,0,0,0,0,0,1,
     & 0,0,0,1,1,0,0,0,1,0,
     & 1,1,0,1,1,1,1,1,1,0,
     & 1,0,1,0,0,1,0,1,1,0,
     & 0,1,0,1,0,1,1,0,0,0,
     & 0,1,0,0,0,1,0,0,1,1,
     & 0,0,1,1,1,1,0,1,0,1,
     & 0,1,0,0,0,0,0,1,1,0,
     & 0,1,1,0,0,0,1,0,0,0,
     & 1,0,1,0,0,0,1,0,1,0,
     & 0,1,1,0,0,1,1,0,0,0,
     & 0,0,1,1,0,1,1,0,1,1,
     & 0,0,0,1,0,0,1,0,0,1,
     & 0,0,0,1,1,0,0,0,0,0,
     & 0,0,1,1,0,1,1,1,1,0,
     & 1,0,1,1,1,1,1,1,1,1,
     & 0,1,0,0,0,1,1,0,1,1,
     & 1,1,0,0,0,0,1,1,1,1,
     & 0,0,1,1,1,0,0,0,1,0,
     & 0,1,1,0,0,0,1,1,0,0,
     & 0,1,1,0,1,1,0,1,1,0,
     & 0,1,0,1,0,0,1,0,0,1,
     & 0,0,0,0,0,0,0,1,1,0,
     & 1,0,0,0,0,1,0,1,0,1,
     & 1,0,0,1,1,0,1,1,0,0,
     & 0,1,0,0,1,1,1,1,0,0,
     & 1,0,0,1,0,1,1,0,0,1,
     & 1,1,0,1,0,1,1,0,0,0,
     & 0,0,1,0,1,0,1,0,1,0,
     & 0,0,0,1,0,0,0,1,1,0,
     & 0,0,1,0,0,1,0,1,1,0,
     & 1,1,1,0,0,0,0,1,0,1,
     & 1,0,0,1,1,0,0,1,1,1,
     & 1,1,1,0,0,1,0,0,1,1,
     & 0,0,1,1,1,1,1,1,0,1,
     & 1,0,0,1,1,1,1,1,1,0,
     & 0,0,1,0,1,1,1,1,1,0,
     & 0,0,1,1,1,0,0,1,1,1,
     & 0,0,1,0,1,0,0,0,0,1,
     & 0,0,1,0,0,0,1,0,1,1,
     & 0,0,1,1,1,0,1,0,1,1,
     & 1,0,1,0,0,1,0,0,1,0,
     & 1,0,1,1,0,1,1,1,1,1,
     & 0,0,1,1,1,0,0,1,0,1,
     & 0,1,1,1,1,0,0,0,0,0,
     & 0,0,0,1,1,0,1,0,1,0,
     & 1,0,0,0,1,0,1,1,1,1,
     & 1,1,1,0,0,0,0,1,0,1,
     & 1,1,1,1,0,0,1,1,0,0,
     & 0,0,0,0,0,0,0,1,1,1,
     & 1,0,0,0,1,1,0,1,0,1,
     & 0,1,0,1,0,0,1,1,0,0,
     & 1,0,0,0,0,0,0,1,0,1,
     & 0,1,0,1,1,1,0,1,0,0,
     & 1,1/
      DATA NAME/'Mary Johns          ','Andrew Richley      ',
     &            'Mary Smith ','John Johnson ',
     &            'Linda Williams ','Barbara Brown ',
     &            'Elizabeth Jones ','David Miller ',
     &            'Richard Davis ','Susan Garcia ',
     &            'Margaret Rodriguez ','Thomas Wilson ',
     &            'Christopher Martinez ','Daniel Anderson ',
     &            'Paul Taylor ','Mark Thomas ',
     &            'Donald Hernandez ','Sandra Moore ',
     &            'Kenneth Martin ','Carol Jackson ',
     &            'Edward Thompson ','Sharon White ',
     &            'Ronald Lopez ','Anthony Lee ',
     &            'Kevin Gonzalez ','Kimberly Harris ',
     &            'Matthew Clark ','Jessica Lewis ',
     &            'Timothy Robinson ','Cynthia Walker ',
     &            'Larry Perez ','Jeffrey Hall ',
     &            'Frank Young ','Amy Allen ',
     &            'Eric Sanchez ','Stephen Wright ',
     &            'Virginia King ','Kathleen Scott ',
     &            'Gregory Green ','Martha Baker ',
     &            'Jerry Adams ','Amanda Nelson ',
     &            'Stephanie Hill ','Carolyn Ramirez ',
     &            'Christine Campbell ','Marie Mitchell ',
     &            'Janet Roberts ','Henry Carter ',
     &            'Carl Phillips ','Ann Evans ',
     &            'Joyce Turner ','Roger Torres ',
     &            'Joe Parker ','Julie Collins ',
     &            'Jack Edwards ','Albert Stewart ',
     &            'Jonathan Flores ','Justin Morris ',
     &            'Terry Nguyen ','Gerald Murphy ',
     &            'Cheryl Rivera ','Samuel Cook ',
     &            'Willie Rogers ','Ralph Morgan ',
     &            'Lawrence Peterson ','Nicholas Cooper ',
     &            'Roy Reed ','Janice Bailey ',
     &            'Kelly Bell ','Brandon Gomez ',
     &            'Adam Kelly ','Harry Howard ',
     &            'Kathy Ward ','Theresa Cox ',
     &            'Beverly Diaz ','Steve Richardson ',
     &            'Louis Wood ','Jeremy Watson ',
     &            'Aaron Brooks ','Randy Bennett ',
     &            'Rachel Gray ','Eugene James ',
     &            'Carlos Reyes ','Kathryn Cruz ',
     &            'Louise Hughes ','Victor Price ',
     &            'Martin Myers ','Ernest Long ',
     &            'Wanda Foster ','Todd Sanders ',
     &            'Jesse Ross ','Craig Morales ',
     &            'Alan Powell ','Tina Sullivan ',
     &            'Clarence Russell ','Sean Ortiz ',
     &            'Paula Jenkins ','Chris Gutierrez ',
     &            'Annie Perry ','Lillian Butler ',
     &            'Jimmy Barnes ','Robin Fisher ',
     &            'Peggy Henderson ','Crystal Coleman ',
     &            'Tony Simmons ','Luis Patterson ',
     &            'Mike Jordan ','Stanley Reynolds ',
     &            'Leonard Hamilton ','Nathan Graham ',
     &            'Dale Kim ','Tiffany Gonzales ',
     &            'Rodney Alexander ','Curtis Ramos ',
     &            'Norman Wallace ','Allen Griffin ',
     &            'Wendy West ','Vincent Cole ',
     &            'Glenn Hayes ','Jeffery Chavez ',
     &            'Travis Gibson ','Jeff Bryant ',
     &            'Chad Ellis ','Thelma Stevens ',
     &            'Shannon Murray ','Sheila Ford ',
     &            'Ethel Marshall ','Ellen Owens ',
     &            'Elaine Mcdonald ','Marjorie Harrison ',
     &            'Jesus Ruiz ','Herbert Kennedy ',
     &            'Frederick Wells ','Esther Alvarez ',
     &            'Pauline Woods ','Emma Mendoza ',
     &            'Juanita Castillo ','Anita Olson ',
     &            'Rhonda Webb ','Hazel Washington ',
     &            'Randall Tucker ','Barry Freeman ',
     &            'Alexander Burns ','Bernard Henry ',
     &            'Mario Vasquez ','Leroy Snyder ',
     &            'Francisco Simpson ','Jamie Crawford ',
     &            'Joanne Jimenez ','Theodore Porter ',
     &            'Valerie Mason ','Danielle Shaw ',
     &            'Megan Gordon ','Jay Wagner ',
     &            'Jim Hunter ','Tom Romero ',
     &            'Gail Hicks ','Alex Dixon ',
     &            'Darlene Hunt ','Ronnie Palmer ',
     &            'Jill Robertson ','Erin Black ',
     &            'Tommy Holmes ','Lauren Stone ',
     &            'Derek Meyer ','Warren Boyd ',
     &            'Darrell Mills ','Lynn Warren ',
     &            'Sally Fox ','Leo Rose ',
     &            'Alvin Rice ','Beatrice Moreno ',
     &            'Wesley Schmidt ','Gordon Patel ',
     &            'Dean Ferguson ','Greg Nichols ',
     &            'Annette Herrera ','Dustin Medina ',
     &            'Pedro Ryan ','Derrick Fernandez ',
     &            'Dana Weaver ','Stacy Daniels ',
     &            'Ana Stephens ','Corey Gardner ',
     &            'Ida Payne ','Maurice Kelley ',
     &            'Vernon Dunn ','Roberto Pierce ',
     &            'Clyde Arnold ','Glen Tran ',
     &            'Loretta Spencer ','Yolanda Peters ',
     &            'Jeanette Hawkins ','Laurie Grant ',
     &            'Rick Hansen ','Lester Castro ',
     &            'Vanessa Hoffman ','Alma Hart ',
     &            'Sue Elliott ','Elsie Cunningham ',
     &            'Beth Knight ','Gene Bradley ',
     &            'Marc Carroll ','Carla Hudson ',
     &            'Ruben Duncan ','Brett Armstrong ',
     &            'Eileen Berry ','Terri Andrews ',
     &            'Gertrude Johnston ','Lucy Ray ',
     &            'Tonya Lane ','Milton Riley ',
     &            'Stacey Carpenter ','Wilma Perkins ',
     &            'Chester Aguilar ','Cecil Silva ',
     &            'Jessie Richards ','Franklin Willis ',
     &            'Agnes Matthews ','Vera Chapman ',
     &            'Brad Lawrence ','Gabriel Garza ',
     &            'Ron Vargas ','Mitchell Watkins ',
     &            'Melinda Wheeler ','Arnold Larson ',
     &            'Harvey Carlson ','Maureen Harper ',
     &            'Colleen George ','Allison Greene ',
     &            'Cory Burke ','Claude Guzman ',
     &            'Georgia Morrison ','Darryl Munoz ',
     &            'Lillie Jacobs ','Neil Obrien ',
     &            'Jackie Lawson ','Marcia Franklin ',
     &            'Tanya Lynch ','Fernando Bishop ',
     &            'Clinton Carr ','Marlene Salazar ',
     &            'Mathew Austin ','Glenda Mendez ',
     &            'Darren Gilbert ','Lonnie Jensen ',
     &            'Lance Williamson ','Marian Montgomery ',
     &            'Julio Harvey ','Caroline Oliver ',
     &            'Kurt Howell ','Jo Dean ',
     &            'Vickie Hanson ','Guy Weber ',
     &            'Terry Garrett ','Hugh Sims ',
     &            'Max Burton ','Mabel Fuller ',
     &            'Marsha Soto ','Armando Mccoy ',
     &            'Felix Welch ','Christy Chen ',
     &            'Everett Schultz ','Jordan Walters ',
     &            'Ian Reid ','Wallace Fields ',
     &            'Ken Walsh ','Nora Little ',
     &            'Margie Fowler ','Nina Bowman ',
     &            'Cassandra Davidson ','Leah May ',
     &            'Dave Day ','Kay Schneider ',
     &            'Priscilla Newman ','Sidney Brewer ',
     &            'Carole Lucas ','Brandy Holland ',
     &            'Olga Wong ','Billie Banks ',
     &            'Clifton Santos ','Tracey Curtis ',
     &            'Daryl Pearson ','Jenny Delgado ',
     &            'Felicia Valdez ','Sonia Pena ',
     &            'Miriam Rios ','Salvador Douglas ',
     &            'Perry Sandoval ','Bobbie Barrett ',
     &            'Sergio Hopkins ','Kristina Keller ',
     &            'Tracy Guerrero ','Seth Stanley ',
     &            'Mae Bates ','Terrance Alvarado ',
     &            'Rene Beck ','Ramona Ortega ',
     &            'Sherri Wade ','Erika Estrada ',
     &            'Freddie Contreras ','Wade Barnett ',
     &            'Lindsey Caldwell ','Lindsay Santiago ',
     &            'Geneva Lambert ','Michael Powers ',
     &            'Belinda Chambers ','David Nunez ',
     &            'Sheryl Craig ','Cora Leonard ',
     &            'Joseph Lowe ','Ada Rhodes ',
     &            'Christopher Byrd ','Daniel Gregory ',
     &            'Paul Shelton ','Mark Frazier ',
     &            'Donald Becker ','Harriet Maldonado ',
     &            'Kenneth Fleming ','Steven Vega ',
     &            'Edward Sutton ','Brian Cohen ',
     &            'Blanche Jennings ','Sandy Parks ',
     &            'Kevin Mcdaniel ','Jason Watts ',
     &            'Iris Barker ','Eunice Norris ',
     &            'Angie Vaughn ','Inez Vazquez ',
     &            'Larry Holt ','Jeffrey Schwartz ',
     &            'Amelia Steele ','Alberta Benson ',
     &            'Genevieve Neal ','Monique Dominguez ',
     &            'Jodi Horton ','Raymond Terry ',
     &            'Maggie Wolfe ','Joshua Hale ',
     &            'Sonya Lyons ','Jan Graves ',
     &            'Lee Haynes ','Patrick Miles ',
     &            'Peter Park ','Fannie Warner ',
     &            'Douglas Padilla ','Henry Bush ',
     &            'Alison Thornton ','Arthur Mccarthy ',
     &            'Ryan Mann ','Luz Zimmerman ',
     &            'Joe Erickson ','Juan Fletcher ',
     &            'Jack Mckinney ','Albert Page ',
     &            'Jonathan Dawson ','Justin Joseph ',
     &            'Lula Marquez ','Gerald Reeves ',
     &            'Verna Klein ','Samuel Espinoza ',
     &            'Willie Baldwin ','Ralph Moran ',
     &            'Juana Love ','Jeannette Robbins ',
     &            'Pam Higgins ','Kelli Ball ',
     &            'Hannah Cortez ','Whitney Le ',
     &            'Bridget Griffith ','Karla Bowen ',
     &            'Fred Sharp ','Latoya Cummings ',
     &            'Patty Ramsey ','Steve Hardy ',
     &            'Louis Swanson ','Della Barber ',
     &            'Aaron Acosta ','Lynne Luna ',
     &            'Sheri Chandler ','Marianne Blair ',
     &            'Kara Daniel ','Jacquelyn Cross ',
     &            'Erma Simon ','Blanca Dennis ',
     &            'Myra Oconnor ','Leticia Quinn ',
     &            'Pat Gross ','Krista Navarro ',
     &            'Roxanne Moss ','Craig Fitzgerald ',
     &            'Johnnie Doyle ','Robyn Mclaughlin ',
     &            'Francis Rojas ','Sean Rodgers ',
     &            'Philip Stevenson ','Chris Singh ',
     &            'Brooke Yang ','Earl Figueroa ',
     &            'Sadie Harmon ','Bernadette Newton ',
     &            'Traci Paul ','Bryan Manning ',
     &            'Tony Garner ','Luis Mcgee ',
     &            'Mike Reese ','Stanley Francis ',
     &            'Chelsea Burgess ','Mable Adkins ',
     &            'Dale Goodman ','Manuel Curry ',
     &            'Rodney Brady ','Elena Christensen ',
     &            'Krystal Potter ','Angelina Walton ',
     &            'Marvin Goodwin ','Vincent Mullins ',
     &            'Glenn Molina ','Jeffery Webster ',
     &            'Paulette Fischer ','Jeff Campos ',
     &            'Chad Avila ','Jacob Sherman ',
     &            'Rosemarie Todd ','Angel Chang ',
     &            'Desiree Blake ','Kyle Malone ',
     &            'Francis Wolf ','Bradley Hodges ',
     &            'Jesus Juarez ','Betsy Gill ',
     &            'Christie Farmer ','Freda Hines ',
     &            'Mercedes Gallagher ','Meredith Duran ',
     &            'Lynette Hubbard ','Eddie Cannon ',
     &            'Ricky Miranda ','Troy Wang ',
     &            'Leigh Saunders ','Barry Tate ',
     &            'Alexander Mack ','Eloise Hammond ',
     &            'Rochelle Carrillo ','Gretchen Townsend ',
     &            'Francisco Wise ','Raquel Ingram ',
     &            'Henrietta Barton ','Theodore Mejia ',
     &            'Jana Ayala ','Kelley Schroeder ',
     &            'Oscar Hampton ','Jay Rowe ',
     &            'Jenna Parsons ','Tom Frank ',
     &            'Laverne Waters ','Alex Strickland ',
     &            'Jon Osborne ','Tasha Maxwell ',
     &            'Silvia Chan ','Lloyd Deleon ',
     &            'Casey Norman ','Leon Harrington ',
     &            'Sophie Casey ','Warren Patton ',
     &            'Darrell Logan ','Jerome Bowers ',
     &            'Floyd Mueller ','Leo Glover ',
     &            'Alvin Floyd ','Lana Hartman ',
     &            'Wesley Buchanan ','Gordon Cobb ',
     &            'Dean French ','Essie Kramer ',
     &            'Mandy Mccormick ','Dustin Clarke ',
     &            'Pedro Tyler ','Derrick Gibbs ',
     &            'Jeannie Moody ','Lewis Conner ',
     &            'Dixie Sparks ','Lucia Mcguire ',
     &            'Herman Leon ','Faith Bauer ',
     &            'Lela Norton ','Johanna Pope ',
     &            'Shari Flynn ','Camille Hogan ',
     &            'Tami Robles ','Shane Salinas ',
     &            'Elisa Yates ','Sam Lindsey ',
     &            'Melba Lloyd ','Lester Marsh ',
     &            'Brent Mcbride ','Tabitha Owen ',
     &            'Charlie Solis ','Jaime Pham ',
     &            'Winifred Lang ','Gene Pratt ',
     &            'Marc Lara ','Alisha Brock ',
     &            'Ruben Ballard ','Rena Trujillo ',
     &            'Angel Shaffer ','Marla Drake ',
     &            'Tammie Roman ','Leslie Aguirre ',
     &            'Edgar Morton ','Milton Stokes ',
     &            'Raul Lamb ','Sherrie Pacheco ',
     &            'Chester Patrick ','Cecil Cochran ',
     &            'Duane Shepherd ','Stacie Cain ',
     &            'Andre Burnett ','Elmer Hess ',
     &            'Shelby Li ','Abigail Cervantes ',
     &            'Ron Olsen ','Mitchell Briggs ',
     &            'Cara Ochoa ','Adele Cabrera ',
     &            'Rebekah Velasquez ','Lucinda Montoya ',
     &            'Adrian Roth ','Chris Meyers ',
     &            'Cory Cardenas ','Trina Fuentes ',
     &            'Erik Weiss ','Shawn Wilkins ',
     &            'Jamie Hoover ','Neil Nicholson ',
     &            'Jessie Underwood ','Christian Short ',
     &            'Javier Carson ','Kerri Morrow ',
     &            'Trisha Colon ','Ted Holloway ',
     &            'Mathew Summers ','Francisca Bryan ',
     &            'Josie Petersen ','Lonnie Mckenzie ',
     &            'Lance Serrano ','Cody Wilcox ',
     &            'Brittney Carey ','Kelly Clayton ',
     &            'Kurt Poole ','Allan Calderon ',
     &            'Helene Gallegos ','Guy Greer ',
     &            'Elva Rivas ','Hugh Guerra ',
     &            'Max Decker ','Dwayne Collier ',
     &            'Bettie Wall ','Armando Whitaker ',
     &            'Aida Bass ','Jimmie Flowers ',
     &            'Everett Davenport ','Iva Conley ',
     &            'Eugenia Houston ','Wallace Huff ',
     &            'Ken Copeland ','Cassie Hood ',
     &            'Maude Monroe ','Casey Massey ',
     &            'Alfredo Roberson ','Alberto Combs ',
     &            'Dave Franco ','Ivan Larsen ',
     &            'Janette Pittman ','Latonya Randall ',
     &            'Byron Skinner ','Morgan Wilkinson ',
     &            'Consuelo Kirby ','Morris Cameron ',
     &            'Rosetta Bridges ','Debora Anthony ',
     &            'Daryl Richard ','Ross Kirk ',
     &            'Virgil Bruce ','Jewell Singleton ',
     &            'Marshall Mathis ','Salvador Bradford ',
     &            'Dorothea Boone ','Kirk Abbott ',
     &            'Sergio Charles ','Esperanza Allison ',
     &            'Tracy Sweeney ','Seth Atkinson ',
     &            'Kent Horn ','Helena Jefferson ',
     &            'Carolina Rosales ','Eduardo York ',
     &            'Terrence Christian ','Enrique Phelps ',
     &            'Freddie Farrell ','James Castaneda ',
     &            'John Nash ','Robert Dickerson ',
     &            'Alisa Bond ','Lou Wyatt ',
     &            'David Foley ','Susanne Chase ',
     &            'Bette Gates ','Susana Vincent ',
     &            'Elise Mathews ','Christopher Hodge ',
     &            'Isabelle Garrison ','Paul Trevino ',
     &            'Jocelyn Villarreal ','Paige Heath ',
     &            'Joni Dalton ','Rachelle Valencia ',
     &            'Leola Callahan ','Daphne Hensley ',
     &            'Alta Atkins ','Ester Huffman ',
     &            'Anthony Roy ','Graciela Boyer ',
     &            'Jason Shields ','Matthew Lin ',
     &            'Gary Hancock ','Lacey Grimes ',
     &            'Glenna Glenn ','Larry Cline ',
     &            'Keri Delacruz ','Ursula Camacho ',
     &            'Lizzie Dillon ','Kirsten Parrish ',
     &            'Stephen Oneill ','Andrew Melton ',
     &            'Raymond Booth ','Gregory Kane ',
     &            'Jaclyn Berg ','Gracie Harrell ',
     &            'Sondra Pitts ','Carmela Savage ',
     &            'Patrick Wiggins ','Peter Brennan ',
     &            'Charity Salas ','Tonia Marks ',
     &            'Beatriz Russo ','Carl Sawyer ',
     &            'Arthur Baxter ','Ryan Golden ',
     &            'Sheena Hutchinson ','Joe Liu ',
     &            'Juan Walter ','Lily Mcdowell ',
     &            'Robbie Wiley ','Jonathan Rich ',
     &            'Justin Humphrey ','Terry Johns ',
     &            'Cathleen Koch ','Angelia Suarez ',
     &            'Samuel Hobbs ','Willie Beard ',
     &            'Ralph Gilmore ','Summer Ibarra ',
     &            'Jodie Keith ','Roy Macias ',
     &            'Lea Khan ','Christi Andrade ',
     &            'Brandon Ware ','Justine Stephenson ',
     &            'Elma Henson ','Fred Wilkerson ',
     &            'Wayne Dyer ','Dominique Mcclure ',
     &            'Steve Blackwell ','Rene Mercado ',
     &            'Jeremy Tanner ','Aaron Eaton ',
     &            'Mavis Clay ','Howard Barron ',
     &            'Eugene Beasley ','Maritza Oneal ',
     &            'Russell Small ','Bobby Preston ',
     &            'Victor Wu ','Martin Zamora ',
     &            'Ernest Macdonald ','Phillip Vance ',
     &            'Todd Snow ','Willa Mcclain ',
     &            'Manuela Stafford ','Alan Orozco ',
     &            'Selma Barry ','Clarence English ',
     &            'Sean Shannon ','Philip Kline ',
     &            'Chris Jacobson ','Dale Woodard ',
     &            'Earl Huang ','Dee Kemp ',
     &            'Antonio Mosley ','Marcy Prince ',
     &            'Luisa Merritt ','Tony Hurst ',
     &            'Luis Villanueva ','Ofelia Roach ',
     &            'Meagan Nolan ','Leonard Lam ',
     &            'Matilda Yoder ','Leila Mccullough ',
     &            'Manuel Lester ','Rodney Santana ',
     &            'Curtis Valenzuela ','Bettye Winters ',
     &            'Allen Barrera ','Marvin Orr ',
     &            'Latisha Leach ','Barbra Berger ',
     &            'Georgina Mckee ','Eliza Strong ',
     &            'Jeff Conway ','Chad Stein ',
     &            'Rhoda Whitehead ','Lee Bullock ',
     &            'Melvin Escobar ','Nola Knox ',
     &            'Kyle Meadows ','Flossie Solomon ',
     &            'Ila Velez ','Jesus Odonnell ',
     &            'Herbert Kerr ','Nelda Stout ',
     &            'Minerva Blankenship ','Lilly Browning ',
     &            'Edwin Kent ','Letha Lozano ',
     &            'Eddie Bartlett ','Estela Pruitt ',
     &            'Valarie Buck ','Randall Barr ',
     &            'Barry Gaines ','Alexander Durham ',
     &            'Bernard Gentry ','Mario Mcintyre ',
     &            'Mia Sloan ','Francisco Rocha ',
     &            'Lidia Melendez ','Micheal Herman ',
     &            'Alexandria Sexton ','Clifford Moon ',
     &            'Tia Hendricks ','Oscar Rangel ',
     &            'Jay Stark ','Jim Lowery ',
     &            'Tom Hardin ','Jami Hull ',
     &            'Alex Sellers ','Jon Ellison ',
     &            'Ronnie Calhoun ','Neva Gillespie ',
     &            'Marylou Mora ','Tommy Knapp ',
     &            'Leon Mccall ','Derek Morse ',
     &            'Avis Dorsey ','Darrell Weeks ',
     &            'Jerome Nielsen ','Jeanie Livingston ',
     &            'Leo Leblanc ','Nannie Mclean ',
     &            'Harriett Bradshaw ','Wesley Glass ',
     &            'Penelope Middleton ','Milagros Buckley ',
     &            'Emilia Schaefer ','Jorge Frost ',
     &            'Dustin Howe ','Pedro House ',
     &            'Derrick Mcintosh ','Tommie Ho ',
     &            'Lewis Pennington ','Karina Reilly ',
     &            'Eve Hebert ','Herman Mcfarland ',
     &            'Maurice Hickman ','Malinda Noble ',
     &            'Noreen Spears ','Clyde Conrad ',
     &            'Glen Arias ','Hillary Galvan ',
     &            'Amie Velazquez ','Althea Huynh ',
     &            'Rosalinda Frederick ','Jordan Randolph ',
     &            'Lilia Cantu ','Brent Fitzpatrick ',
     &            'Ramon Mahoney ','Clare Peck ',
     &            'Tyler Villa ','Gilbert Michael ',
     &            'Michael Donovan ','Lorrie Mcconnell ',
     &            'Reginald Walls ','Ruben Boyle ',
     &            'Earnestine Mayer ','Carmella Zuniga ',
     &            'Taylor Giles ','Noemi Pineda ',
     &            'Marcie Pace ','Liza Hurley ',
     &            'Milton Mays ','Louisa Mcmillan ',
     &            'Earlene Crosby ','Chester Ayers ',
     &            'Cecil Case ','Nita Bentley ',
     &            'Selena Shepard ','Tanisha Everett ',
     &            'Katy Pugh ','Julianne David ',
     &            'John Mcmahon ','Ron Dunlap ',
     &            'Mitchell Bender ','Roland Hahn ',
     &            'Margery Harding ','Harvey Acevedo ',
     &            'Dollie Raymond ','Roxie Blackburn ',
     &            'Roslyn Duffy ','Kathrine Landry ',
     &            'Nanette Dougherty ','Erik Bautista ',
     &            'Darryl Shah ','Jamie Potts ',
     &            'Kris Arroyo ','Tammi Valentine ',
     &            'Suzette Meza ','Javier Gould ',
     &            'Fernando Vaughan ','Jerry Fry ',
     &            'Merle Rush ','Chrystal Avery ',
     &            'Tyrone Herring ','Darren Dodson ',
     &            'Lilian Clements ','Lance Sampson ',
     &            'Aline Tapia ','Julio Bean ',
     &            'Kelly Lynn ','Kurt Crane ',
     &            'Allan Farley ','Colette Cisneros ',
     &            'Guy Benton ','Clayton Ashley ',
     &            'Yesenia Mckay ','Max Finley ',
     &            'Dwayne Best ','Dwight Blevins ',
     &            'Eddie Friedman ','Felix Moses ',
     &            'Valeria Sosa ','Nona Blanchard ',
     &            'Jordan Huber ','Ian Frye ',
     &            'Georgette Krueger ','Claudine Bernard ',
     &            'Fran Rosario ','Jaime Rubio ',
     &            'Roseann Mullen ','Alfredo Benjamin ',
     &            'Susanna Haley ','Reva Chung ',
     &            'Deidre Moyer ','Johnnie Choi ',
     &            'Sheree Horne ','Byron Yu ',
     &            'Julian Woodward ','Elvia Ali ',
     &            'Morris Nixon ','Clifton Hayden ',
     &            'Gena Rivers ','Daryl Estes ',
     &            'Araceli Mccarty ','Virgil Richmond ',
     &            'Rosanne Stuart ','Wendi Maynard ',
     &            'Salvador Brandt ','Berta Oconnell ',
     &            'Marva Hanna ','Imelda Sanford ',
     &            'Marietta Sheppard ','Marci Church ',
     &            'Seth Burch ','Kent Levy ',
     &            'Sasha Rasmussen ','Madelyn Coffey ',
     &            'Janna Ponce ','Terrence Faulkner ',
     &            'Enrique Donaldson ','Aurelia Schmitt ',
     &            'Wade Novak ','Augusta Costa ',
     &            'John Montes ','Young Booker ',
     &            'Christian Cordova ','Lessie Waller ',
     &            'Amalia Arellano ','Richard Maddox ',
     &            'Charles Mata ','Joseph Bonilla ',
     &            'Thomas Stanton ','Christopher Compton ',
     &            'Daniel Kaufman ','Paul Dudley ',
     &            'Mark Mcpherson ','Leanna Beltran ',
     &            'Carey Dickson ','Kenneth Mccann ',
     &            'Coleen Villegas ','Edward Proctor ',
     &            'Aisha Hester ','Ronald Cantrell ',
     &            'Karyn Daugherty ','Kevin Cherry ',
     &            'Jason Bray ','Matthew Davila ',
     &            'Mai Rowland ','Timothy Madden ',
     &            'Rosanna Levine ','Hallie Spence ',
     &            'Erna Good ','Enid Irwin ',
     &            'Mariana Werner ','Lacy Krause ',
     &            'Juliet Petty ','Andrew Whitney ',
     &            'Raymond Baird ','Gregory Hooper ',
     &            'Joshua Pollard ','Hester Zavala ',
     &            'Dennis Jarvis ','Lelia Holden ',
     &            'Casandra Haas ','Bridgett Hendrix ',
     &            'Angelita Mcgrath ','Jannie Bird ',
     &            'Henry Lucero ','Carl Terrell ',
     &            'Katina Riggs ','Beryl Joyce ',
     &            'Roger Mercer ','Joe Rollins ',
     &            'Juan Galloway ','Jack Duke ',
     &            'Albert Odom ','Jonathan Andersen ',
     &            'Justin Downs ','Terry Hatfield ',
     &            'Gerald Benitez ','Gilda Archer ',
     &            'Adrian Huerta ','Rhea Travis ',
     &            'Marquita Mcneil ','Lawrence Hinton ',
     &            'Nicholas Zhang ','Roy Hays ',
     &            'Angelique Mayo ','Francesca Fritz ',
     &            'Brandon Branch ','Kaitlin Mooney ',
     &            'Harry Ewing ','Florine Ritter ',
     &            'Wayne Esparza ','Reyna Frey ',
     &            'Steve Braun ','Fanny Gay ',
     &            'Jeremy Riddle ','Aaron Haney ',
     &            'Concetta Kaiser ','Bertie Holder ',
     &            'Eugene Chaney ','Carlos Mcknight ',
     &            'Alyson Gamble ','Bobby Vang ',
     &            'Victor Cooley ','Martin Carney ',
     &            'Ernest Cowan ','Phillip Forbes ',
     &            'Todd Ferrell ','Deann Davies ',
     &            'Craig Barajas ','Louella Shea ',
     &            'Shawn Osborn ','Felecia Bright ',
     &            'Sean Cuevas ','Lesa Bolton ',
     &            'Beverley Murillo ','Robert Lutz ',
     &            'Earl Duarte ','Herminia Kidd ',
     &            'Antonio Key ','Danny Cooke ',
     &            'Luna Andrews        ','Camilla reds        '/
      CALL INIRAN
        OPEN(11,FILE=SFN,ERR=9000)
        DO 10,I=1,N
            IF(SEX(I).EQ.0)THEN
              IF (MOD(I,2).EQ.0) THEN
                TEMPN = NAME(I)
              ELSE
                TEMPN = NAME(I+1)
              END IF
            ELSE IF (SEX(I).EQ.0)THEN
              IF (MOD(I,2).EQ.1) THEN
                TEMPN = NAME(I)
              ELSE
                TEMPN = NAME(I+1)
              END IF
            ELSE
            END IF
            JS(I)=GRC(5)+1
            AGE(I)=GRC(40)+15
c            PRINT *,'JS = ',JS(I)
            IF (JS(I).EQ.1) THEN
C              WRITE(11,*,ERR=9100) 'NAME             ','  SEX '
C     &,' JS',' AGE'
              WRITE(11,110,ERR=9100) NAME(I),SEX(I),JS(I),AGE(I)
            ELSE IF (JS(I).EQ.2) THEN
              SALARY(I)=800+GRC(1500)
C              WRITE(11,*,ERR=9100) 'NAME             ','  SEX '
C     &,' JS',' SALARY'
                WRITE(11,120,ERR=9100) NAME(I),SEX(I),JS(I),SALARY(I)
            ELSE IF (JS(I).EQ.3) THEN
              SALARY(I)=500+GRC(1000)
              OSAL(I)=500+GRC(500)
C              WRITE(11,*,ERR=9100) 'NAME             ','  SEX '
C     &,' JS',' SALARY',' OSAL'
                WRITE(11,130,ERR=9100) NAME(I),SEX(I),JS(I),SALARY(I)
     & ,OSAL(I)
            ELSE IF (JS(I).EQ.4) THEN
              NMU(I)=1+GRC(48)
C              WRITE(11,*,ERR=9100) 'NAME             ','  SEX '
C     &,' JS',' AGE',' NMU'
                WRITE(11,140,ERR=9100) NAME(I),SEX(I),JS(I),AGE(I)
     & ,NMU(I)
            ELSE IF (JS(I).EQ.5) THEN
            NWC(I)=1+GRC(3)
C              WRITE(11,*,ERR=9100) 'NAME             ','  SEX '
C     &,' JS',' AGE',' NWC'
                WRITE(11,150,ERR=9100) NAME(I),SEX(I),JS(I),AGE(I)
     & ,NWC(I)
            ELSE
                PRINT *,'ILLEGAL JOB STATUS',JS(I)
            END IF
10      CONTINUE
        WRITE(11,160,ERR=9100) 9,' '
        CLOSE(11)
        GOTO 9999
110   FORMAT(A20,2X,I1,1X,I1,2X,I2)
120   FORMAT(A20,2X,I1,1X,I1,2X,I4)
130   FORMAT(A20,2X,I1,1X,I1,2X,I4,2X,I4)
140   FORMAT(A20,2X,I1,1X,I1,2X,I2,2X,I3)
150   FORMAT(A20,2X,I1,1X,I1,2X,I2,1X,I1)
160   FORMAT(22X,I1,10X,A1)
9000  PRINT *,'ERROR IN OPENING SURVEY DATA FILE',SFN
      GOTO 9999
9100  PRINT *,'ERROR IN WRITING SURVEY DATA'
9999  STOP
      END
